version: '2'
# Only  use this file for subsequent starts
services:
    wildfly:
      image: jboss/wildfly:10.1.0.Final
      links:
        - keycloak
      ports:
        - "8080:8080"
        - "9990:9990"
      volumes:
        - ./volumes/sqrl-server:/opt/jboss/sqrl-server
      environment:
        JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8787
        idphost: keycloak
        idpport: 8080
      env_file:
        - ./volumes/sqrl-server/sqrl-server.properties
      depends_on:
        - keycloak
    keycloak:
        # Keycloak image might be built prior to starting this file.
        image: sqrl/keycloak:1.0.0-SNAPSHOT
        ports:
            - "8081:8080"
            - "9991:9990"
            - "8787:8787"
        volumes:
            # Startup script is stored in this directory.
            - ./volumes/idp-server/pre-deploy:/opt/jboss/keycloak/pre-deploy
            # Directory for the storage of keycloak generated configuration for sqrl-server
            - ./volumes/idp-server/data:/opt/jboss/keycloak/standalone/data
        environment:
            JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8787
            IDP_CONFIG_DIR: /opt/jboss/keycloak/standalone/data
        env_file:
            # For the productive environment, these properties muss be passed to the docker container -e
            - ./volumes/sqrl-server/sqrl-server.properties
        entrypoint: /opt/jboss/keycloak/pre-deploy/docker-entrypoint.sh
        command: -b 0.0.0.0 -bmanagement 0.0.0.0 -c standalone-ha.xml
            